# -*- coding: utf-8 -*-
import os
import sys

from PySide6 import QtGui
################################################################################
## Form generated from reading UI file 'Key BindingsfTTbKf.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_Key_Bindings(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(496, 311)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(320, 260, 161, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 190, 101, 16))
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 220, 101, 16))
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit = QLineEdit(Dialog)
        self.ui_lineEdit.setObjectName(u"ui_lineEdit")
        self.ui_lineEdit.setGeometry(QRect(130, 190, 51, 22))
        self.ui_lineEdit_2 = QLineEdit(Dialog)
        self.ui_lineEdit_2.setObjectName(u"ui_lineEdit_2")
        self.ui_lineEdit_2.setGeometry(QRect(130, 220, 51, 22))
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(190, 190, 41, 24))
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(190, 220, 41, 24))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 170, 471, 81))
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(420, 50, 41, 24))
        self.ui_lineEdit_3 = QLineEdit(self.groupBox)
        self.ui_lineEdit_3.setObjectName(u"ui_lineEdit_3")
        self.ui_lineEdit_3.setGeometry(QRect(360, 20, 51, 22))
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(420, 20, 41, 24))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 20, 101, 16))
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(240, 50, 111, 16))
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_4 = QLineEdit(self.groupBox)
        self.ui_lineEdit_4.setObjectName(u"ui_lineEdit_4")
        self.ui_lineEdit_4.setGeometry(QRect(360, 50, 51, 22))
        self.pushButton_5 = QPushButton(Dialog)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(430, 50, 41, 24))
        self.ui_lineEdit_5 = QLineEdit(Dialog)
        self.ui_lineEdit_5.setObjectName(u"ui_lineEdit_5")
        self.ui_lineEdit_5.setGeometry(QRect(370, 50, 51, 22))
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(250, 110, 111, 16))
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_6 = QLineEdit(Dialog)
        self.ui_lineEdit_6.setObjectName(u"ui_lineEdit_6")
        self.ui_lineEdit_6.setGeometry(QRect(370, 110, 51, 22))
        self.pushButton_6 = QPushButton(Dialog)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(430, 110, 41, 24))
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 20, 101, 16))
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(250, 0, 231, 171))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 140, 111, 16))
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_9 = QLineEdit(self.groupBox_2)
        self.ui_lineEdit_9.setObjectName(u"ui_lineEdit_9")
        self.ui_lineEdit_9.setGeometry(QRect(120, 140, 51, 22))
        self.pushButton_9 = QPushButton(self.groupBox_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(180, 140, 41, 24))
        self.ui_lineEdit_7 = QLineEdit(Dialog)
        self.ui_lineEdit_7.setObjectName(u"ui_lineEdit_7")
        self.ui_lineEdit_7.setGeometry(QRect(370, 80, 51, 22))
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(260, 50, 101, 16))
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_8 = QLineEdit(Dialog)
        self.ui_lineEdit_8.setObjectName(u"ui_lineEdit_8")
        self.ui_lineEdit_8.setGeometry(QRect(370, 20, 51, 22))
        self.pushButton_7 = QPushButton(Dialog)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(430, 80, 41, 24))
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 80, 101, 16))
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_8 = QPushButton(Dialog)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(430, 20, 41, 24))
        self.pushButton_10 = QPushButton(Dialog)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(190, 20, 41, 24))
        self.ui_lineEdit_10 = QLineEdit(Dialog)
        self.ui_lineEdit_10.setObjectName(u"ui_lineEdit_10")
        self.ui_lineEdit_10.setGeometry(QRect(130, 110, 51, 22))
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 20, 101, 16))
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_11 = QPushButton(Dialog)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(190, 110, 41, 24))
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 50, 101, 16))
        self.label_11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_11 = QLineEdit(Dialog)
        self.ui_lineEdit_11.setObjectName(u"ui_lineEdit_11")
        self.ui_lineEdit_11.setGeometry(QRect(130, 50, 51, 22))
        self.ui_lineEdit_12 = QLineEdit(Dialog)
        self.ui_lineEdit_12.setObjectName(u"ui_lineEdit_12")
        self.ui_lineEdit_12.setGeometry(QRect(130, 20, 51, 22))
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 110, 111, 16))
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_12 = QPushButton(Dialog)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(190, 50, 41, 24))
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 80, 101, 16))
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_13 = QPushButton(Dialog)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(190, 80, 41, 24))
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 231, 171))
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 140, 111, 16))
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ui_lineEdit_13 = QLineEdit(self.groupBox_3)
        self.ui_lineEdit_13.setObjectName(u"ui_lineEdit_13")
        self.ui_lineEdit_13.setGeometry(QRect(120, 140, 51, 22))
        self.pushButton_14 = QPushButton(self.groupBox_3)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(180, 140, 41, 24))
        self.ui_lineEdit_14 = QLineEdit(Dialog)
        self.ui_lineEdit_14.setObjectName(u"ui_lineEdit_14")
        self.ui_lineEdit_14.setGeometry(QRect(130, 80, 51, 22))
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 260, 201, 31))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.pushButton_15 = QPushButton(self.frame)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 0, 101, 24))
        self.pushButton_16 = QPushButton(self.frame)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(120, 0, 75, 24))
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.buttonBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.ui_lineEdit.raise_()
        self.ui_lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.ui_lineEdit_5.raise_()
        self.label_5.raise_()
        self.ui_lineEdit_6.raise_()
        self.pushButton_6.raise_()
        self.label_6.raise_()
        self.ui_lineEdit_7.raise_()
        self.label_7.raise_()
        self.ui_lineEdit_8.raise_()
        self.pushButton_7.raise_()
        self.label_8.raise_()
        self.pushButton_8.raise_()
        self.pushButton_10.raise_()
        self.ui_lineEdit_10.raise_()
        self.label_10.raise_()
        self.pushButton_11.raise_()
        self.label_11.raise_()
        self.ui_lineEdit_11.raise_()
        self.ui_lineEdit_12.raise_()
        self.label_12.raise_()
        self.pushButton_12.raise_()
        self.label_13.raise_()
        self.pushButton_13.raise_()
        self.ui_lineEdit_14.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.pushButton_12.clicked.connect(self.ui_lineEdit_11.clear)
        self.pushButton_10.clicked.connect(self.ui_lineEdit_12.clear)
        self.pushButton_13.clicked.connect(self.ui_lineEdit_14.clear)
        self.pushButton_11.clicked.connect(self.ui_lineEdit_10.clear)
        self.pushButton_14.clicked.connect(self.ui_lineEdit_13.clear)
        self.pushButton_8.clicked.connect(self.ui_lineEdit_8.clear)
        self.pushButton_5.clicked.connect(self.ui_lineEdit_5.clear)
        self.pushButton_7.clicked.connect(self.ui_lineEdit_7.clear)
        self.pushButton_6.clicked.connect(self.ui_lineEdit_6.clear)
        self.pushButton_9.clicked.connect(self.ui_lineEdit_9.clear)
        self.pushButton.clicked.connect(self.ui_lineEdit.clear)
        self.pushButton_2.clicked.connect(self.ui_lineEdit_2.clear)
        self.pushButton_4.clicked.connect(self.ui_lineEdit_4.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_2.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_13.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_10.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_11.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_12.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_4.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_9.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_7.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_6.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_5.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_8.clear)
        self.pushButton_3.clicked.connect(self.ui_lineEdit_3.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_3.clear)
        self.pushButton_16.clicked.connect(self.ui_lineEdit_14.clear)

        self.pushButton.setDefault(False)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowIcon(QtGui.QIcon(resource_path("joystick_icon.png")))
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Key Bindings", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Left Eyebrow", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Right Eyebrow", None))
        self.ui_lineEdit.setText(QCoreApplication.translate("Dialog", u"{65}", None))
        self.ui_lineEdit.setPlaceholderText("")
        self.ui_lineEdit_2.setText(QCoreApplication.translate("Dialog", u"{68}", None))
        self.ui_lineEdit_2.setPlaceholderText("")
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Eyebrows", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.ui_lineEdit_3.setText(QCoreApplication.translate("Dialog", u"{87}", None))
        self.ui_lineEdit_3.setPlaceholderText("")
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Raised Eyebrows", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Furrowed Eyebrows", None))
        self.ui_lineEdit_4.setText(QCoreApplication.translate("Dialog", u"{83}", None))
        self.ui_lineEdit_4.setPlaceholderText("")
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.ui_lineEdit_5.setText(QCoreApplication.translate("Dialog", u"{76}", None))
        self.ui_lineEdit_5.setPlaceholderText("")
        self.label_5.setText(QCoreApplication.translate("Dialog", u"3 Fingers Up", None))
        self.ui_lineEdit_6.setText(QCoreApplication.translate("Dialog", u"{79}", None))
        self.ui_lineEdit_6.setPlaceholderText("")
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"0 Fingers Up", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Right Hand", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"4 Fingers Up", None))
        self.pushButton_9.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.ui_lineEdit_7.setText(QCoreApplication.translate("Dialog", u"{13}", None))
        self.ui_lineEdit_7.setPlaceholderText("")
        self.label_7.setText(QCoreApplication.translate("Dialog", u"1 Finger Up", None))
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"2 Fingers Up", None))
        self.pushButton_8.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.pushButton_10.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.ui_lineEdit_10.setText(QCoreApplication.translate("Dialog", u"{73}", None))
        self.ui_lineEdit_10.setPlaceholderText("")
        self.label_10.setText(QCoreApplication.translate("Dialog", u"0 Fingers Up", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"1 Finger Up", None))
        self.ui_lineEdit_11.setInputMask("")
        self.ui_lineEdit_11.setText(QCoreApplication.translate("Dialog", u"{75}", None))
        self.ui_lineEdit_11.setPlaceholderText("")
        self.label_12.setText(QCoreApplication.translate("Dialog", u"3 Fingers Up", None))
        self.pushButton_12.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"2 Fingers Up", None))
        self.pushButton_13.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Left Hand", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"4 Fingers Up", None))
        self.pushButton_14.setText(QCoreApplication.translate("Dialog", u"Clear", None))
        self.ui_lineEdit_14.setText(QCoreApplication.translate("Dialog", u"{8}", None))
        self.ui_lineEdit_14.setPlaceholderText("")
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Reset Defaults", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"Clear All", None))
    # retranslateUi


def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
